apiVersion: apps/v1
kind: Deployment
metadata:
  name: Store-management-deployment
  labels:
    app: Store-management
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: Store-management
  template:
    metadata:
      labels:
        app: Store-management
    spec:
      containers:
        - name: Store-management
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          
          # Recommended for Java/Spring Boot apps
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10