apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-management-deployment
  labels:
    app: store-management
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: store-management
  template:
    metadata:
      labels:
        app: store-management
    spec:
      containers:
        - name: store-management
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: rds-db-credentials
                  key: url 
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rds-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-db-credentials
                  key: password

          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          
          # Recommended for Java/Spring Boot apps
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10